### ISSUE TITLE
Add Google Analytics script and allow user to add their GA id in config

### ISSUE THREAD

**Issue by nicknish** [yogodoshi/cansei#24]

**Comment by yogodoshi** [comment]
I think it's a nice to have something like a counter on how many people joined the movement and/or tweets have been sent is more useful: both for converting new users and to see the movement growing; it also doesn't require a setup/knowledge like analytics does. But we could have both in the future 👍 #my2cents

**Comment by nicknish** [comment]
As far as the UX: It can simply be a blank field in the setup YAML and if someone adds their GA ID then it will simply start working (at least with page views).

Let me know if you want to do this and I'll add it.

> counter

I think the counter is a great idea, but I think that idea is more for the visitors as social-proof than it is for the owner. I think both have a place.

**Comment by yogodoshi** [comment]
> I think the counter is a great idea, but I think that idea is more for the visitors as social-proof than it is for the owner.

Yeah, that's how I see it too but I also think it helps the owner to feel more empowered, seeing the number grow (as it would grow even without new user's joining), it would give the owner a feeling of "the movement is growing everyday, with every tweet" I guess 😛 

I just don't think that people would really want GA as it's not like a real project they would wanna see it grow, keep checking metrics and all, that's why I would prioritize the counter which also wouldn't require any sign-up on third parties neither additional setup and it serve both purposes (social proof and see how its growing) :)
